services:
  db:
    image: postgres:latest
    container_name: movies_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - movies_db_data:/var/lib/postgresql/data

volumes:
  movies_db_data:
    driver: local